CREATE TABLE FILEUPLOAD (
	IDX INTEGER,
	FILENAME VARCHAR2(255) NULL,
	FILEREALNAME VARCHAR2(255) NULL,
	DOWNLOADCOUNT INTEGER DEFAULT 0,
	CONSTRAINT FILEUPLOAD_PK PRIMARY KEY (IDX)
);

DELETE FROM FILEUPLOAD;
DROP SEQUENCE fileupload_idx_seq;
CREATE SEQUENCE fileupload_idx_seq;

SELECT * FROM FILEUPLOAD;

