CREATE TABLE "REGISTER" (
    "USERID" VARCHAR2(30 BYTE) NOT NULL, 
	"USERPASSWORD" VARCHAR2(30 BYTE) NOT NULL, 
	"USERNAME" VARCHAR2(30 BYTE) NOT NULL, 
	"USERAGE" NUMBER(*,0) NOT NULL, 
	"USERGENDER" CHAR(6 BYTE) NOT NULL, 
	"USEREMAIL" VARCHAR2(30 BYTE) NOT NULL, 
	CONSTRAINT "REGISTER_PK" PRIMARY KEY ("USERID")
);

DELETE FROM register;
DROP SEQUENCE register_idx_seq;
CREATE SEQUENCE register_idx_seq;





